name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Sleep for random time
      run: |
        MAX_SLEEP=$((6*60*60)) # 6 hours in seconds (GitHub Actions max runtime)
        SLEEP_TIME=$(($RANDOM % $MAX_SLEEP))
        echo "Sleeping for $SLEEP_TIME seconds..."
        sleep $SLEEP_TIME

    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
